   MODULE FBS_QDLDL_Interface

   INTERFACE

      SUBROUTINE FBS_QDLDL ( CALLING_SUBR, MATIN_NAME, NROWS, NTERMS, I_MATIN, J_MATIN, MATIN, ICOL, RHS_COL, INFO )

      USE PENTIUM_II_KIND, ONLY       :  LONG, DOUBLE
      USE IOUNT1, ONLY                :  ERR, F06, SC1
      USE SCONTR, ONLY                :  BLNK_SUB_NAM, FATAL_ERR
      USE SuperLU_STUF, ONLY          :  SLU_FACTORS

      IMPLICIT NONE

      CHARACTER(LEN=*), INTENT(IN)    :: CALLING_SUBR
      CHARACTER(LEN=*), INTENT(IN)    :: MATIN_NAME

      INTEGER(LONG), INTENT(IN)       :: ICOL
      INTEGER(LONG), INTENT(IN)       :: NROWS
      INTEGER(LONG), INTENT(IN)       :: NTERMS
      INTEGER(LONG), INTENT(IN)       :: I_MATIN(NROWS+1)
      INTEGER(LONG), INTENT(IN)       :: J_MATIN(NTERMS)
      INTEGER(LONG), INTENT(INOUT)    :: INFO

      REAL(DOUBLE),  INTENT(IN)       :: MATIN(NTERMS)
      REAL(DOUBLE),  INTENT(IN)       :: RHS_COL(NROWS)

      END SUBROUTINE FBS_QDLDL

   END INTERFACE

   END MODULE FBS_QDLDL_Interface
