   MODULE SYM_MAT_DECOMP_QDLDL_Interface

   INTERFACE

      SUBROUTINE SYM_MAT_DECOMP_QDLDL ( CALLING_SUBR, MATIN_NAME, MATIN_SET, NROWS, NTERMS, I_MATIN, J_MATIN, MATIN, INFO )

      USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG, DOUBLE
      USE IOUNT1, ONLY                :  ERR, F06, SC1
      USE SCONTR, ONLY                :  BLNK_SUB_NAM, FATAL_ERR
      USE PARAMS, ONLY                :  BAILOUT
      USE SuperLU_STUF, ONLY          :  SLU_FACTORS, QDLDL_NEG_COUNT

      IMPLICIT NONE

      CHARACTER(LEN=*), INTENT(IN)    :: CALLING_SUBR
      CHARACTER(LEN=*), INTENT(IN)    :: MATIN_NAME
      CHARACTER(LEN=*), INTENT(IN)    :: MATIN_SET

      INTEGER(LONG), INTENT(IN)       :: NROWS
      INTEGER(LONG), INTENT(IN)       :: NTERMS
      INTEGER(LONG), INTENT(IN)       :: I_MATIN(NROWS+1)
      INTEGER(LONG), INTENT(IN)       :: J_MATIN(NTERMS)
      INTEGER(LONG), INTENT(INOUT)    :: INFO

      REAL(DOUBLE),  INTENT(IN)       :: MATIN(NTERMS)

      END SUBROUTINE SYM_MAT_DECOMP_QDLDL

   END INTERFACE

   END MODULE SYM_MAT_DECOMP_QDLDL_Interface
